redux
htmlacademy-react/113758-six-cities-5 pull request #9
Opened 2020-11-12 21:43 UTC by norzserge

2020-11-14 17:36 UTC, obzhorash requested changes

2020-11-14 17:36 UTC, obzhorash commented on src/components/app/app.jsx
> +const url = `https://5.react.pages.academy/six-cities/hotels`;
Выносим в отдельный модуль констант и название в верхнем регистре

2020-11-14 17:36 UTC, obzhorash commented on src/components/app/app.jsx
> +  }).catch(alert);
фетчём на курсе не пользуемся, далее используем axios, на данном этапе нам не нужны данные с сервера, пользумся моками
Демонстрация работа с сервером будет далее в курсе

2020-11-14 17:36 UTC, obzhorash commented on src/components/cities-list/cities-list.jsx
> +    const initActiveTab = document.querySelector(`.tabs__item`);
на прямую к DOM обращаться нельзя, для обращения к DOM используются Ref (https://ru.reactjs.org/docs/refs-and-the-dom.html) Важно обрати внимание КОГДА используются рефы
добавлять классы можно по условию прям в JSX, создать стэйт в котором хранить текущий активный таб(первый по дефолту) при клике менять активный, и в разметки по условию отображать(почитаю про JSX)

2020-11-15 08:17 UTC, norzserge commented on src/components/app/app.jsx
> +  }).catch(alert);
Не понял немного. Там же в задании написано:

> Создайте новый компонент «Список городов». Компонент получает все необходимые данные через props. **Список городов формируется на основании данных, полученных с сервера.** Сервер всегда возвращает информацию только для шести городов. Не забудьте написать проверку всех props.

2020-11-15 18:21 UTC, norzserge commented on src/components/app/app.jsx
> +  }).catch(alert);
Заменил фетч на моки

2020-11-15 23:06 UTC, merged